sites:
  Technews 科技新報:
    url: https://technews.tw/category/business/
  ithome:
    url: https://www.ithome.com.tw/news
  Inside 硬塞的:
    url: https://www.inside.com.tw/
  Cool3cTkbang:
    url: https://www.cool3c.com/
  FreeCodeCamp:
    url: https://www.freecodecamp.org/news/
  Computer King Ada (電腦王阿達):
    url: https://www.kocpc.com.tw/category/news
    
  # Facebook Pages/Groups
  facebook:
    # Set to true to enable "Doom Scroll" on personal feed
    feed_enabled: true
    scroll_count: 15
    groups:
     - https://www.facebook.com/groups/baogo.developer
     - https://www.facebook.com/groups/ChatGPT.TW
     - https://www.facebook.com/Microsoft.Student.Ambassadors.TW
     - https://www.facebook.com/groups/1089148002685934

ai:
  enabled: true
  api_key: "YOUR_GEMINI_API_KEY"

system:
  rate_limit_delay: 8
  
cookies_file: "cookies.json"
